version: '3'
services:
  app:
    image: weyoppanel-img
    container_name: weyoppanel-container
    build: ./
    restart: always
    ports:
      - "85:80"
    networks:
      - allnet
    volumes:
      - .:/var/www/html
  myadmin:
    image: phpmyadmin
    container_name: weyoppanel-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "82:80"
    networks:
      - allnet
    links:
      - mysql:db
  mysql:
    container_name: weyoppanel-mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3305:3306
    networks:
      - allnet
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: Rut123.
volumes:
    mysql:
      driver: "local"
networks:
  allnet: null