version: '3'
services:
  app:
    image: kamikaze-img
    container_name: kamikaze-container
    build: ./
    restart: always
    ports:
      - "118:80"
    volumes:
      - .:/var/www/html
  myadmin:
    image: phpmyadmin
    container_name: kamikaze-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "119:80"
    links:
      - mysql:db
  # mysql:
  #   container_name: marcantonio-mysql
  #   image: mysql:5.6
  #   restart: always
  #   ports:
  #     - 3308:3306
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_HOST: 0.0.0.0
  #     MYSQL_ROOT_PASSWORD: Rut123.
volumes:
    mysql:
      driver: "local"
networks:
  default:
    name: wxpanel_kaminet